### ISSUE TITLE
Activity 1: Your First Caption

### ISSUE THREAD

**Issue by githubteacher** [githubschool/march-9th#5]
Using the API, I have just created a file with a random octocat for you to caption. In this activity, we will learn how to make changes to files in our GitHub repository.

- [ ] @beardofedu
- [ ] @satyapenta
- [ ] @FShenoda
- [ ] @peterhugger
- [ ] @BinduTuli0609
- [ ] @a00125970
- [ ] @NowshadAzimi
- [ ] @wsmith2
- [ ] @chinrung
- [ ] @RonkasPSEG
- [ ] @designMoreWeb
- [ ] @Gymky
- [ ] @MatthewSchlosserPSEG
- [ ] @derekacevedo
- [ ] @Shdesai36
- [ ] @shreykhu
- [ ] @TerHano
- [ ] @arch02
- [ ] @awhite575
- [ ] @wsmith2
- [ ] @beardofedu
- [ ] @Mike-the-powerful
- [ ] @XinyuXiong
- [ ] @beardofedu
- [ ] @beardofedu

**Comment by beardofedu** [comment]
XAT-123

**Comment by beardofedu** [comment]
XAT-123
